FROM ubuntu
# FROM eclipse-temurin:latest

# If using eclipse-temurin image delete the following lines
RUN apt-get update
RUN apt-get -y install default-jre
RUN apt-get -y install curl
RUN apt-get -y install tar

RUN curl https://dlcdn.apache.org/kafka/3.2.1/kafka_2.13-3.2.1.tgz --output kafka.tgz

RUN mkdir kafka

RUN tar -xvzf kafka.tgz --strip-components=1 -C ./kafka
RUN rm kafka.tgz

COPY ./start.sh ./start.sh
RUN chmod 755 ./start.sh
CMD ./start.sh